# Generated by Django 4.2.5 on 2023-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_all_app', '0002_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
