# Generated by Django 4.2.5 on 2023-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_all_app', '0007_remove_temp_total_temp_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='order_num',
            field=models.IntegerField(null=True),
        ),
    ]
